# Generated by Django 5.0.4 on 2024-05-26 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=20)),
                ('card_type', models.CharField(default='credit', max_length=10)),
                ('credit_limit', models.FloatField(default=1000.0)),
                ('balance', models.FloatField(default=0.0)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_record',
            fields=[
                ('transfer_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_in_id', models.IntegerField()),
                ('account_out_id', models.IntegerField()),
                ('transfer_amount', models.IntegerField()),
                ('transfer_date', models.DateTimeField()),
            ],
        ),
    ]
