# Generated by Django 5.0.4 on 2024-05-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transfer_record',
            new_name='Transaction',
        ),
    ]
