# Generated by Django 5.0.4 on 2024-05-27 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0002_rename_transfer_record_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='name', max_length=20)),
                ('identity_card', models.CharField(default='000000000000000000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Online_user',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_card', models.CharField(default='000000000000000000', max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditCardExaminer',
            fields=[
                ('credit_examiner_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_authority', models.BooleanField(default=False)),
                ('account', models.CharField(default='000000', max_length=30)),
                ('password', models.CharField(default='password', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_status', models.BooleanField(default=False)),
                ('apply_result', models.BooleanField(default=False)),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creditCardExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.creditcardexaminer')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.online_user')),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='online_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creditcard.online_user'),
        ),
        migrations.CreateModel(
            name='SystemManager',
            fields=[
                ('sys_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(default='000000', max_length=30)),
                ('password', models.CharField(default='password', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.employee')),
            ],
        ),
    ]
